# Generated by Django 6.0.5 on 2026-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblLabTest',
            fields=[
                ('LabTestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReferenceRanges', models.TextField()),
                ('SampleType', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
    ]
