# Generated by Django 6.0.5 on 2026-05-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMedicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=100)),
                ('ManufacturingDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('Unit', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblMedicineStock',
            fields=[
                ('MedicineStockId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('IsLowStock', models.BooleanField(default=False)),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.tblmedicine')),
            ],
        ),
    ]
