# Generated by Django 6.0.5 on 2026-05-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_technician', '0001_initial'),
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblConsultation',
            fields=[
                ('ConsultationId', models.AutoField(primary_key=True, serialize=False)),
                ('Symptoms', models.TextField()),
                ('Diagnosis', models.TextField()),
                ('Notes', models.TextField(blank=True, null=True)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblappointment')),
            ],
        ),
        migrations.CreateModel(
            name='TblLabTestPrescription',
            fields=[
                ('LabTestPrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('LabTestValue', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblappointment')),
                ('LabTestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_technician.tbllabtest')),
            ],
        ),
        migrations.CreateModel(
            name='TblMedicinePrescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=100)),
                ('Frequency', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblappointment')),
            ],
        ),
    ]
