# Generated by Django 6.0.5 on 2026-05-19 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblSpecialization',
            fields=[
                ('SpecializationId', models.AutoField(primary_key=True, serialize=False)),
                ('SpecializationName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TblStaff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EmpID', models.CharField(max_length=50, unique=True)),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_module.tblrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblDoctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('StaffId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SpecializationId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_module.tblspecialization')),
            ],
        ),
    ]
