# Generated by Django 6.0.5 on 2026-05-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMembership',
            fields=[
                ('MembershipId', models.AutoField(primary_key=True, serialize=False)),
                ('MembershipName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblAppointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
                ('TokenNumber', models.IntegerField(blank=True, null=True)),
                ('ConsultationStatus', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='TblBilling',
            fields=[
                ('BillingId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('RegistrationCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AdditionalCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('BillingDate', models.DateField(auto_now_add=True)),
                ('AppointmentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblappointment')),
            ],
        ),
        migrations.CreateModel(
            name='TblPatient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('MembershipId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receptionist.tblmembership')),
            ],
        ),
        migrations.AddField(
            model_name='tblappointment',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.tblpatient'),
        ),
    ]
